package com.familyvault.entity;

public enum AuditAction {
    LOGIN,
    FAMILY_CREATED,
    MEMBER_REGISTERED,
    FOLDER_CREATED,
    FOLDER_UPDATED,
    FOLDER_DELETED,
    FILE_UPLOADED,
    FILE_DOWNLOADED,
    FILE_UPDATED,
    FILE_DELETED,
    EMERGENCY_REQUESTED,
    EMERGENCY_APPROVED,
    EMERGENCY_UNLOCKED,
    EMERGENCY_DOWNLOAD
}
